version: "3.7"
services:
  app:
    image: kooldev/node:14-nest
    command:
    - npm
    - run
    - start:dev
    ports:
    - ${KOOL_APP_PORT:-4000}:4000
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
    volumes:
    - .:/app:delegated
    networks:
    - kool_local
    - kool_global
volumes:
  database: null
networks:
  kool_local: null
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
